name: Publish Docker image to AWS ECR
on:
  push:
  pull_request:
jobs:

  push_to_registry:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build Docker Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t 2020

   push_image:
      name: Push Docker image
      runs-on: ubuntu-latest
      needs: build_image
      if: github.ref == 'refs/heads/main'
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2
  
        - name: Push Docker Image
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: |
            aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
            rev=$(git rev-parse --short HEAD)
            docker tag 2020 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kandidat-2020:$rev
            docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kandidat-2020:$rev