name: Sam Workflow
on:
  push:
    branches:
      - master
  pull_request:
defaults:
  run:
    working-directory: ./kjell

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - run: sam build --use-container
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-app-2020 --s3-bucket kandidat-2020  --capabilities CAPABILITY_IAM --region eu-west-1
      - name: sam deploy
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-app-2020 --s3-bucket kandidat-2020  --capabilities CAPABILITY_IAM --region eu-west-1
